[project]
name = "moon-multipython-monorepo-example"
version = "0.1.0"
description = "Multi-python monorepo demoing proto, moon (and pre-commit)"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "pre-commit>=4.3.0",
]

[tool.uv]
python-preference = "only-system"
