#!/usr/bin/env bash
set -eo pipefail

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

echo --% >/dev/null;: ' | out-null
uv run pre-commit run --hook-stage commit-msg --commit-msg-filename $1
<#'
# unix-like shells
exit $? #>
# powershell
uv run pre-commit run --hook-stage commit-msg --commit-msg-filename $args[1]
